-- MySQL Script generated by MySQL Workbench
-- Thu Aug 30 21:28:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dti17
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dti17
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dti17` DEFAULT CHARACTER SET utf8 ;
USE `dti17` ;

-- -----------------------------------------------------
-- Table `dti17`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dti17`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dti17`.`Registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dti17`.`Registro` (
  `idRegistro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cold` INT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idRegistro`),
  INDEX `fk_Registro_endereco_idx` (`endereco_idendereco` ASC),
  CONSTRAINT `fk_Registro_endereco`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `dti17`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dti17`.`Localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dti17`.`Localizacao` (
  `idLocalizacao` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `pontuacao` INT NULL,
  PRIMARY KEY (`idLocalizacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dti17`.`Comunicados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dti17`.`Comunicados` (
  `idComunicados` INT NOT NULL AUTO_INCREMENT,
  `nomeInfo` VARCHAR(45) NULL,
  `comunicado` VARCHAR(45) NULL,
  `moradores` VARCHAR(45) NULL,
  `horasDispo` VARCHAR(5) NULL,
  `descricao` TEXT(200) NULL,
  `Registro_idRegistro` INT NOT NULL,
  `Localizacao_idLocalizacao` INT NOT NULL,
  PRIMARY KEY (`idComunicados`),
  INDEX `fk_Comunicados_Registro1_idx` (`Registro_idRegistro` ASC),
  INDEX `fk_Comunicados_Localizacao1_idx` (`Localizacao_idLocalizacao` ASC),
  CONSTRAINT `fk_Comunicados_Registro1`
    FOREIGN KEY (`Registro_idRegistro`)
    REFERENCES `dti17`.`Registro` (`idRegistro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comunicados_Localizacao1`
    FOREIGN KEY (`Localizacao_idLocalizacao`)
    REFERENCES `dti17`.`Localizacao` (`idLocalizacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dti17`.`Reunioes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dti17`.`Reunioes` (
  `idReunioes` INT NOT NULL AUTO_INCREMENT,
  `daata` VARCHAR(20) NULL,
  `horario` VARCHAR(45) NULL,
  `local` VARCHAR(45) NULL,
  `assuntos` VARCHAR(45) NULL,
  `Registro_idRegistro` INT NOT NULL,
  PRIMARY KEY (`idReunioes`),
  INDEX `fk_Reunioes_Registro1_idx` (`Registro_idRegistro` ASC),
  CONSTRAINT `fk_Reunioes_Registro1`
    FOREIGN KEY (`Registro_idRegistro`)
    REFERENCES `dti17`.`Registro` (`idRegistro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dti17`.`Estatistica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dti17`.`Estatistica` (
  `idEstatistica` INT NOT NULL AUTO_INCREMENT,
  `Localizacao_idLocalizacao` INT NOT NULL,
  PRIMARY KEY (`idEstatistica`),
  INDEX `fk_Estatistica_Localizacao1_idx` (`Localizacao_idLocalizacao` ASC),
  CONSTRAINT `fk_Estatistica_Localizacao1`
    FOREIGN KEY (`Localizacao_idLocalizacao`)
    REFERENCES `dti17`.`Localizacao` (`idLocalizacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
